name: publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        website: [ modrinth, curseforge ]
        loader: [ Forge, Fabric ]
    name: ${{ matrix.website }} (${{ matrix.loader }})
    
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk 17
        uses: actions/setup-java@v1
        with:
          java-version: "17"
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
        
      - name: Publish Modrinth Release
        uses: Kir-Antipov/mc-publish@v3.3
        if: matrix.website == 'modrinth'
        with:
          modrinth-id: t6BIRVZn
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files: |
            ${{ matrix.loader }}/build/libs/!(*-@(dev|sources|javadoc)).jar
            ${{ matrix.loader }}/build/libs/*-@(dev|sources|javadocs).jar
          version-type: release
          java: Java 17
          name: ""
          changelog: CHANGELOG.md
          
      - name: Publish Curseforge Release
        uses: Kir-Antipov/mc-publish@v3.3
        if: matrix.website == 'curseforge'
        with:
          curseforge-id: 362528
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          files: |
            ${{ matrix.loader }}/build/libs/!(*-@(dev|sources|javadoc)).jar
            ${{ matrix.loader }}/build/libs/*-@(dev|sources|javadocs).jar
          version-type: release
          java: Java 17
          name: ""
          changelog: CHANGELOG.md
